version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    versioning-strategy: increase
    open-pull-requests-limit: 100
    labels:
      - 'javascript'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      major:
        update-types: ['major']
      minor:
        update-types: ['minor']
      patch:
        update-types: ['patch']

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    open-pull-requests-limit: 100
    labels:
      - 'github_actions'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      dependencies:
        dependency-type: 'production'