minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"
title                    : &name "Wasiq Bhamla"
title_separator          : "|"
subtitle                 : "Open source contributor | Mentor | Senior QA Consultant at ThoughtWorks"
name                     : *name
description              : &description "Senior QA Consultant at ThoughtWorks"
url                      : "https://wasiqb.github.io"
repository               : "WasiqB/wasiqb.github.io"
teaser                   : /assets/images/home_banner.jpg
breadcrumbs              : false
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "https-wasiqb-github-io"
reCaptcha:
  siteKey                : 6Leu6z8UAAAAAPVQTbLQ8ZuhLe4Ui7WciKu0jNVI
  secret                 : 6Leu6z8UAAAAAGr40US3aarh3Cd8iXjgvwEWCf5v
atom_feed:
  path                   : "http://feeds.feedburner.com/WasiqBhamla"
search                   : true
search_full_content      : true
search_provider          : algolia
algolia:
  application_id         : JYM5MTO78V
  index_name             : prod_wasiqb
  search_only_api_key    : 151917eaa9d78486b1148fe818088aa3
  powered_by             : true
  extensions_to_index    :
    - html
    - md
  files_to_exclude       : []

# SEO Related
google_site_verification : i3x-x1g3IFyNUzu6z4EMXpwviY9o7FrCYkBXDNq90wE

# Social Sharing
twitter:
  username               : WasiqBhamla

social:
  type                   : Person
  name                   : *name
  links:
    - &linkedin "https://www.linkedin.com/in/wasiqbhamla"
    - &twitter "https://twitter.com/WasiqBhamla"
    - &facebook "https://www.facebook.com/wasiqb"
    - &github "https://github.com/WasiqB"
    - &stackoverflow "https://stackoverflow.com/users/5320558/wasiq-bhamla"

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-111539609-1"
    anonymize_ip         : true

# Site Author
author:
  name             : *name
  avatar           : "https://github.com/WasiqB.png"
  bio              : *description
  location         : "Mumbai, India"
  email            : &email "wasbhamla2005@gmail.com"
  links:
    - label: "LinkedIn"
      icon: &img_in "fab fa-linkedin"
      url: *linkedin
    - label: "GitHub"
      icon: &img_gh "fab fa-fw fa-github"
      url: *github
    - label: "StackOverflow"
      icon: &img_so "fab fa-stack-overflow"
      url: *stackoverflow
    - label: "Facebook"
      icon: &img_fb "fab fa-fw fa-facebook-square"
      url: *facebook
    - label: "Twitter"
      icon: &img_tw "fab fa-fw fa-twitter-square"
      url: *twitter

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: *img_in
      url: *linkedin
    - label: "GitHub"
      icon: *img_gh
      url: *github
    - label: "StackOverflow"
      icon: *img_so
      url: *stackoverflow
    - label: "Facebook"
      icon: *img_fb
      url: *facebook
    - label: "Twitter"
      icon: *img_tw
      url: *twitter
    - label: "Sitemap"
      icon: "fas fa-sitemap"
      url: /sitemap.xml

# Reading Files
include:
  - .htaccess
  - _pages
  - _projects
  - _appium
  - _selenium
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /blogs/page:num/
timezone: Asia/Kolkata

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  appium:
    output: true
    permalink: /:collection/:path/
  selenium:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blogs/:title
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # Appium
  - scope:
      path: ""
      type: appium
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: "appium"
  # Selenium
  - scope:
      path: ""
      type: selenium
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc: true
      toc_sticky: true
      sidebar:
        nav: "selenium"
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: splash
      author_profile: true
      classes: wide
