name: Test Deployment

on:
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: pnpm i

      - name: Run lint
        run: pnpm lint

      - name: Run prettier
        run: pnpm prettier

      - name: Build
        run: pnpm build
